name: Build artifacts

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  cli_version:
    name: Extract CLI version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - id: cli_version
      run: |
        cargo metadata --no-deps --format-version 1 | jq -r '.packages[] | select(.name == "zeekstd_cli") | "version=" + .version' | tee -a $GITHUB_OUTPUT
    outputs:
      version: ${{ steps.cli_version.outputs.version }}

  build:
    name: Build ${{ matrix.target }}
    needs: cli_version
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
          - target: aarch64-apple-darwin
            runner: macos-latest
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.ACCESS_TOKEN }}

      - name: Build static binary
        run: |
          nix build --print-build-logs \
            --out-link zeekstd-v${{ needs.cli_version.outputs.version }}-${{ matrix.target }}.tar.gz \
            .#zeekstd-static.tarball

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: zeekstd-v${{ needs.cli_version.outputs.version }}-${{ matrix.target }}.tar.gz
          archive: false

  build-windows:
    name: Build x86_64-pc-windows-msvc
    needs: cli_version
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Build static binary
        run: cargo build --release --package zeekstd_cli
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"

      - name: Compress with 7z
        shell: pwsh
        run: |
          $outName = "zeekstd-v${{ needs.cli_version.outputs.version }}-x86_64-pc-windows-msvc.zip"
          7z a -tzip $outName "./target/release/zeekstd.exe"

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: zeekstd-v${{ needs.cli_version.outputs.version }}-x86_64-pc-windows-msvc.zip
          archive: false

  release:
    name: Publish release assets
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download All
        uses: actions/download-artifact@v8
        with:
          path: artifacts
          merge-multiple: true
          skip-decompress: true

      - name: Publish release assets
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          draft: true
          files: "artifacts/*"
          token: ${{ secrets.GITHUB_TOKEN }}
